from datetime import date
import pandas as pd

start_date = date(2026, 1, 1)
end_date = date(2026, 1, 10)
idx = pd.date_range(start=start_date, end=end_date, freq='D')
df = pd.DataFrame({'calendar_date': idx})
df['calendar_date'] = df['calendar_date'].dt.date
df['year'] = df['calendar_date'].apply(lambda d: d.year)
df['quarter'] = df['calendar_date'].apply(lambda d: (d.month - 1) // 3 + 1)
df['month'] = df['calendar_date'].apply(lambda d: d.month)
df['month_name'] = df['calendar_date'].apply(lambda d: d.strftime('%B'))
df['day'] = df['calendar_date'].apply(lambda d: d.day)
df['day_of_week'] = df['calendar_date'].apply(lambda d: d.isoweekday())
df['day_name'] = df['calendar_date'].apply(lambda d: d.strftime('%A'))
df['weekday'] = df['calendar_date'].apply(lambda d: d.weekday())
df['is_weekend'] = df['weekday'].apply(lambda w: w >= 5)
df['is_month_start'] = df['calendar_date'].apply(lambda d: d.day == 1)
df['is_month_end'] = df['calendar_date'].apply(lambda d: (d + pd.Timedelta(days=1)).month != d.month)
df['week_num'] = df['calendar_date'].apply(lambda d: d.isocalendar()[1])
df['year_month'] = df['calendar_date'].apply(lambda d: d.strftime('%Y-%m'))
df['year_quarter'] = df['calendar_date'].apply(lambda d: f"{d.year}-Q{(d.month - 1) // 3 + 1}")
df['iso_week'] = df['calendar_date'].apply(lambda d: d.isocalendar()[1])
df['iso_year'] = df['calendar_date'].apply(lambda d: d.isocalendar()[0])
print(df.head(10).to_string(index=False))
